#!/system/bin/sh
#

insmod /system/lib/modules/tun.ko
insmod /system/lib/modules/btusb.ko
insmod /system/lib/modules/ath3k.ko
insmod /system/lib/modules/xpad.ko
insmod /system/lib/modules/pl2303.ko
insmod /system/lib/modules/cp210x.ko

echo "done Additional Modules Autoload"
